# Generated by Django 2.2.1 on 2019-08-07 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('description', models.CharField(max_length=40, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Vigente')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre del concurso')),
                ('date_from', models.DateTimeField(verbose_name='Desde')),
                ('date_to', models.DateTimeField(verbose_name='Hasta')),
                ('inscription_date_from', models.DateTimeField(verbose_name='Inscripcion desde')),
                ('inscription_date_to', models.DateTimeField(verbose_name='Inscripcion_hasta')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='cnq.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=70, verbose_name='Cuerpo')),
                ('title', models.CharField(max_length=20, verbose_name='Titulo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post', to='cnq.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role_choices', models.IntegerField(choices=[(0, 'Anonimo'), (1, 'Participant'), (2, 'Tutor'), (3, 'Mentor')], default=0, verbose_name='Rol')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_role', to='cnq.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role_choices', models.IntegerField(choices=[(0, 'Anonimo'), (1, 'Participant'), (2, 'Tutor'), (3, 'Mentor')], default=0, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('max_uses', models.IntegerField(null=True, verbose_name='Usos maximos')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_token', to='cnq.Group')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_uses', to='cnq.GroupToken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_uses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nombre')),
                ('street_name', models.CharField(max_length=40, verbose_name='Direccion')),
                ('street_number', models.IntegerField(verbose_name='Altura')),
                ('school_types', models.IntegerField(choices=[(0, 'Publica'), (1, 'Privada'), (2, 'Tecnica Publica'), (3, 'Tecnica Privada'), (4, 'Escuela Rural'), (5, 'Residencia'), (6, 'Tecnica Privada')], verbose_name='Tipo de escuela')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_location', to='cnq.City')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_school', to='cnq.Group')),
            ],
        ),
        migrations.CreateModel(
            name='RawProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('problem', models.CharField(max_length=70, verbose_name='Problema')),
                ('solution', models.CharField(max_length=150, verbose_name='Solucion')),
                ('diffusion', models.IntegerField(choices=[(0, 'Mail'), (1, 'Afiches del concurso'), (2, 'Redes Sociales'), (3, 'Medios de comunicacion tradicionales'), (4, 'He participado en años anteriores')], verbose_name='Difusion')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_project', to='cnq.Group')),
            ],
        ),
        migrations.CreateModel(
            name='RawParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=15, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=12, verbose_name='Dni')),
                ('grade_choices', models.IntegerField(choices=[(0, '4to'), (1, '5to'), (2, '6to'), (3, '7mo')], verbose_name='Año')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_participant', to='cnq.Group')),
            ],
        ),
        migrations.CreateModel(
            name='RawContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phone_field.models.PhoneField(max_length=31, verbose_name='Numero del tutor')),
                ('alternative_email', models.EmailField(max_length=70, verbose_name='Mail del tutor alternativo')),
                ('alternative_phone_number', phone_field.models.PhoneField(max_length=31, verbose_name='Numero del tutor alternativo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_contact_data', to='cnq.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='cnq.Category')),
                ('raw_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='cnq.RawProject')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50, verbose_name='Cuerpo')),
                ('group_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='cnq.GroupPost')),
                ('group_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='cnq.GroupRole')),
            ],
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_attachment', to='cnq.GroupPost')),
            ],
        ),
        migrations.AddField(
            model_name='grouppost',
            name='group_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post', to='cnq.GroupRole'),
        ),
        migrations.CreateModel(
            name='ContestWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_winner', to='cnq.Contest')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_winner', to='cnq.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ContestFinalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_finalist', to='cnq.Contest')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_finalist', to='cnq.Group')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='cnq.State'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
