# Generated by Django 2.2.1 on 2019-06-12 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproject',
            name='diffusion',
            field=models.IntegerField(choices=[(0, 'Mail'), (1, 'Afiches del concurso'), (2, 'Redes Sociales'), (3, 'Medios de comunicacion tradicionales'), (4, 'He participado en años anteriores')], default=3, verbose_name='Difusion'),
        ),
        migrations.AddField(
            model_name='rawschool',
            name='com_preference',
            field=models.IntegerField(choices=[(0, 'Telefonica'), (1, 'Email'), (2, 'Otro')], default=0, verbose_name='Preferencia de la comunicacion'),
        ),
        migrations.AddField(
            model_name='rawschool',
            name='school_types',
            field=models.IntegerField(choices=[(0, 'Publica'), (1, 'Privada'), (2, 'Tecnica Publica'), (3, 'Tecnica Privada'), (4, 'Escuela Rural'), (5, 'Residencia'), (6, 'Tecnica Privada')], default=0, verbose_name='Tipo de escuela'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='group_role_choices',
            field=models.IntegerField(choices=[(0, 'Anonimo'), (1, 'Participant'), (2, 'Tutor'), (3, 'Mentor')], default=0, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='grouptoken',
            name='group_role_choices',
            field=models.IntegerField(choices=[(0, 'Anonimo'), (1, 'Participant'), (2, 'Tutor'), (3, 'Mentor')], default=0, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='rawparticipant',
            name='divition_choices',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C')], default=0, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='rawparticipant',
            name='email',
            field=models.EmailField(max_length=20, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rawparticipant',
            name='grade_choices',
            field=models.IntegerField(choices=[(0, '4to'), (1, '5to'), (2, '6to'), (3, '7mo')], default=0, verbose_name='Año'),
        ),
        migrations.CreateModel(
            name='TokenUses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_token_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_grouptokenTokenUses', to='cnq.GroupToken')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_userTokenUses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
