# Generated by Django 2.2.1 on 2019-07-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='inscription_date_from',
            field=models.DateTimeField(verbose_name='Inscripcion desde'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='inscription_date_to',
            field=models.DateTimeField(verbose_name='Inscripcion_hasta'),
        ),
    ]
