# Generated by Django 2.2.1 on 2019-06-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplocation',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_location', to='cnq.Group'),
        ),
        migrations.AlterField(
            model_name='rawproject',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_project', to='cnq.Group'),
        ),
        migrations.AlterField(
            model_name='rawschool',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_school', to='cnq.Group'),
        ),
    ]
