# Generated by Django 2.2.1 on 2019-05-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnq', '0002_tokenuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenuses',
            old_name='user',
            new_name='user_id',
        ),
    ]
