# Generated by Django 2.2.1 on 2019-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnq', '0003_auto_20190618_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Vigente'),
        ),
    ]
