# Generated by Django 2.2.1 on 2019-06-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnq', '0003_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
    ]
