# Generated by Django 2.2.1 on 2019-06-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnq', '0005_auto_20190629_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
